---
# Live Apps Web Inventory
# Web tier: Web servers, CDN, Static content

all:
  children:
    apps_web:
      children:
        web_servers:
          hosts:
            web01.live.apps.local:
              ansible_host: 10.2.1.10
            web02.live.apps.local:
              ansible_host: 10.2.1.11
            web03.live.apps.local:
              ansible_host: 10.2.1.12
        static_servers:
          hosts:
            static01.live.apps.local:
              ansible_host: 10.2.1.20

      vars:
        environment: live
        environment_tier: apps
        compartment: apps-web
        ansible_user: ansible
        ansible_become: true
