---
# Shared Inventory
# Common resources and configurations across all environments

all:
  children:
    shared:
      children:
        monitoring:
          hosts:
            prometheus01.shared.local:
              ansible_host: 10.0.1.10
            grafana01.shared.local:
              ansible_host: 10.0.1.11
        logging:
          hosts:
            elasticsearch01.shared.local:
              ansible_host: 10.0.1.20
            kibana01.shared.local:
              ansible_host: 10.0.1.21
        ci_cd:
          hosts:
            jenkins01.shared.local:
              ansible_host: 10.0.1.30
            nexus01.shared.local:
              ansible_host: 10.0.1.31

      vars:
        environment: shared
        environment_tier: shared
        compartment: shared
        ansible_user: ansible
        ansible_become: true
