---
# Live Apps API Inventory
# API tier: API servers, Microservices, Message queues

all:
  children:
    apps_api:
      children:
        api_servers:
          hosts:
            api01.live.apps.local:
              ansible_host: 10.2.2.10
            api02.live.apps.local:
              ansible_host: 10.2.2.11
            api03.live.apps.local:
              ansible_host: 10.2.2.12
        queue_servers:
          hosts:
            rabbitmq01.live.apps.local:
              ansible_host: 10.2.2.20
            rabbitmq02.live.apps.local:
              ansible_host: 10.2.2.21

      vars:
        environment: live
        environment_tier: apps
        compartment: apps-api
        ansible_user: ansible
        ansible_become: true
