---
# Live Platform Storage Inventory
# Storage services: NFS, S3-compatible, Backup

all:
  children:
    platform_storage:
      children:
        nfs_servers:
          hosts:
            nfs01.live.platform.local:
              ansible_host: 10.1.4.10
            nfs02.live.platform.local:
              ansible_host: 10.1.4.11
        s3_servers:
          hosts:
            minio01.live.platform.local:
              ansible_host: 10.1.4.20
            minio02.live.platform.local:
              ansible_host: 10.1.4.21
        backup_servers:
          hosts:
            backup01.live.platform.local:
              ansible_host: 10.1.4.30

      vars:
        environment: live
        environment_tier: platform
        compartment: platform-storage
        ansible_user: ansible
        ansible_become: true
