---
# Live Platform Network Inventory
# Network services: VPN, Load Balancers, Routers, Proxies

all:
  children:
    platform_network:
      children:
        load_balancers:
          hosts:
            lb01.live.platform.local:
              ansible_host: 10.1.2.10
              lb_role: primary
            lb02.live.platform.local:
              ansible_host: 10.1.2.11
              lb_role: secondary
        vpn_servers:
          hosts:
            vpn01.live.platform.local:
              ansible_host: 10.1.2.20
        proxy_servers:
          hosts:
            proxy01.live.platform.local:
              ansible_host: 10.1.2.30
            proxy02.live.platform.local:
              ansible_host: 10.1.2.31

      vars:
        environment: live
        environment_tier: platform
        compartment: platform-network
        ansible_user: ansible
        ansible_become: true
