---
# Live Platform Security Inventory
# Security services: Firewalls, WAF, SIEM, Vault

all:
  children:
    platform_security:
      children:
        firewalls:
          hosts:
            fw01.live.platform.local:
              ansible_host: 10.1.3.10
            fw02.live.platform.local:
              ansible_host: 10.1.3.11
        waf_servers:
          hosts:
            waf01.live.platform.local:
              ansible_host: 10.1.3.20
        siem_servers:
          hosts:
            siem01.live.platform.local:
              ansible_host: 10.1.3.30
        vault_servers:
          hosts:
            vault01.live.platform.local:
              ansible_host: 10.1.3.40
            vault02.live.platform.local:
              ansible_host: 10.1.3.41

      vars:
        environment: live
        environment_tier: platform
        compartment: platform-security
        ansible_user: ansible
        ansible_become: true
