---
# Live Apps Data Inventory
# Data tier: Databases, Caches, Search

all:
  children:
    apps_data:
      children:
        postgresql_servers:
          hosts:
            pg01.live.apps.local:
              ansible_host: 10.2.3.10
              pg_role: primary
            pg02.live.apps.local:
              ansible_host: 10.2.3.11
              pg_role: replica
        redis_servers:
          hosts:
            redis01.live.apps.local:
              ansible_host: 10.2.3.20
            redis02.live.apps.local:
              ansible_host: 10.2.3.21
        elasticsearch_servers:
          hosts:
            es01.live.apps.local:
              ansible_host: 10.2.3.30
            es02.live.apps.local:
              ansible_host: 10.2.3.31

      vars:
        environment: live
        environment_tier: apps
        compartment: apps-data
        ansible_user: ansible
        ansible_become: true
