---
- name: Verify - Windows
  hosts: all
  gather_facts: true
  tasks:
    - name: Check Windows version
      ansible.builtin.debug:
        msg: "Running on {{ ansible_distribution | default('Windows') }}"

    - name: Verify PowerShell available
      ansible.windows.win_shell: |
        $PSVersionTable.PSVersion.ToString()
      register: ps_version

    - name: Display PowerShell version
      ansible.builtin.debug:
        var: ps_version.stdout
