---
# Live Platform Core Inventory
# Core infrastructure services: DNS, DHCP, Time, Authentication

all:
  children:
    platform_core:
      children:
        dns_servers:
          hosts:
            dns01.live.platform.local:
              ansible_host: 10.1.1.10
            dns02.live.platform.local:
              ansible_host: 10.1.1.11
        dhcp_servers:
          hosts:
            dhcp01.live.platform.local:
              ansible_host: 10.1.1.20
        ntp_servers:
          hosts:
            ntp01.live.platform.local:
              ansible_host: 10.1.1.30
        auth_servers:
          hosts:
            ldap01.live.platform.local:
              ansible_host: 10.1.1.40
            ldap02.live.platform.local:
              ansible_host: 10.1.1.41

      vars:
        environment: live
        environment_tier: platform
        compartment: platform-core
        ansible_user: ansible
        ansible_become: true
